# This workflow will build the primary Java file (DemonstrateCachingAndDataPrefetching)

name: Build

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 13.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 13
        java-package: jdk 
        architecture: x64 
    - name: Compile primary JAVA file
      working-directory: ./src
      run: javac DemonstrateCachingAndDataPrefetching.java
